# @info
# master & pull_request jobs cannot de-dupe their workflow configuration :(
# https://github.community/t5/GitHub-Actions/Start-a-workflow-from-another-workflow/td-p/37586
name: master
on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      # https://github.com/JamesIves/github-pages-deploy-action#getting-started-airplane
      - name: checkout 🛎️
        uses: actions/checkout@v2
        with:
          persist-credentials: false
      - uses: actions/setup-node@master
        with:
          node-version: 12.16.1
      - name: install
        run: npm ci
      - name: build
        run: npm run build
      - name: test
        run: npm run test
      - uses: actions/checkout@master
      - uses: codecov/codecov-action@v1
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
